### ISSUE TITLE
 buildToolsVersion is not specified.

### ISSUE THREAD

**Issue by edgaru** [Clip-sub/react-native-shake#2]
Versions:
"react": "16.3.0-alpha.1",
"react-native": "0.54.2",
"react-native-shake": "^3.2.1"

Output:
Scanning folders for symlinks in C:\Users\xxxxx\Documents\react\testshake\node_modules (38ms)
Starting JS server...
Building and installing the app on the device (cd android && gradlew.bat installDebug)...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
\> Could not resolve all dependencies for configuration ':app:_debugApk'.
       \> A problem occurred configuring project ':react-native-shake'.
            \> buildToolsVersion is not specified.

**Comment by Doko-Demo-Doa** [comment]
Fixed. It should be on npm now, please update your package. Thank you.
